### ISSUE TITLE
Meeting tracker

### ISSUE THREAD

**Issue by ramyaragupathy** [varshalalwani/Overscripted-Data-Analysis-Challenge#1]
**Action items for Wednesday (20-Jun)**
- [ ] understand [data](https://github.com/mozilla/Overscripted-Data-Analysis-Challenge#accessing-the-data) and [problem area](https://medium.com/firefox-context-graph/overscripted-digging-into-javascript-execution-at-scale-2ed508f21862)
- [ ] understand [previous analysis](https://medium.com/firefox-context-graph/overscripted-digging-into-javascript-execution-at-scale-2ed508f21862)
- [ ] Get a hang of web dev and javascript - _[How JS works](https://www.youtube.com/watch?v=b1ieJtIx1NY)_, _[Udacity's web development videos](https://www.youtube.com/watch?v=dtiKDBO4nMc&list=PLAwxTw4SYaPlLXUhUNt1wINWrrH9axjcI)_
- [ ] explore options for where would we do the analysis - colab vs own machines vs other
- [ ] @sacmax to create project cards

cc @varshalalwani @sacmax
